### PR TITLE
Add --json output option to dfm, rs41 and rs92 demodulators.

### PR DESCRIPTION
**Pull request by darksidelemm**
I figured it was about time I submitted a PR for the main changes I've made to the various demodulator code, that is - adding in JSON output for easier parsing of the decoded telemetry!

This adds the --json option to the DFM09, RS92, and RS41 demodulators in the demod directory.

### CODE REVIEW

**Comment by rs1729** [comment]
rs41: I would put the json-line at the end of the frame (is an additional LF ok to separate the frames?)
frame-numer/id should also be checked.

Didn't look at dfm09, yet. The problem there: The 1-sec frame has several subframes. The data is displayed when subframe 8 is decoded. So if some subframe is dropped, the frames could differ for different receivers/users.

**Comment by darksidelemm** [comment]
Hmm, I guess we'll have to see how much the dropped-subframe issues with the DFMs occur in practice. Good point though... 

No problems splitting the JSON line out as much as necessary, or moving it around. All we do is look for lines that start with the '{' character and attempt to decode them as JSON. All other lines are ignored.

**Comment by rs1729** [comment]
Included the following in dfm09dm_dft:
--auto: auto-detect polarity (-vv to show polarity)
--dist: outputs only gps-subframes that belong to the same frame.
Further it counts the corrected bits per gps-block. There is a threshold, so if there are to many repairs, the block is marked as suspicious. As explained before, if there are to many errors, the Hamming code might be decoded to the wrong codeword.
You have to decide if you want to have as many frames as possible with potentially incorrect data, or if you take only frames with subframes all without error, or something in between. For weak signals there is always a trade-off.

--json is like --dist in order to output comparable frames. It might be not 100%, and temperature is not checked this way. Sonde-ID is another problem. If the frequency is changed or another DFM on the same frequency becomes dominant, the old ID might persist for some frames.
And before the first ID is decoded, the dummy-ID will be in the json-output.

Pilotsondes don't have temperature sensors. I put in a check similar to the one for the rs41.

-R outputs the 9 gps-blocks as raw data. Together with --ecc you get the number of corrected bits for each block.

Depending on the signal quality and receiver/software-output, some parameters could be tweaked for better performance. The rtl_fm-output does not decode as well as the sdrsharp-output as far as I tested. But it is difficult to compare with signals on air anyway, maybe I need an offline version of rtl_fm. Different demodulators and sharp low pass filters could also affect dft_detect.

rtl_fm:
One might think it would be best to resample to integer multiples, something like
rtl_fm -s48k -r12k/-r16k | sox -r back to 48k.
I think default -s is 24k, but -s48k didn't improve decoding. Maybe -s24k fits better to the baseband sampling rate. The -r decimation is a better lowpass than sox-lowpass afterwards but the results are not quite what I would expect, maybe I should take a deeper look in the source code.

**Comment by darksidelemm** [comment]
OK, so the implication here is that we should just be able to use the --auto option, and ignore the inverted flag which is returned by rs_detect?
Edit: Yep. Some testing with the DFM17 samples shows this to be the case! Nice job!

**Comment by rs1729** [comment]
There was still a minor problem: when decoding with --auto a dfm09 and switching to a dfm06, the new sonde_id was not changed. So I changed the --auto ID-detection, it now detects the ID in a more general way. The ID is always the last subframe, following a xx00000 subframe. In my archives this null-subframe is 5A00000 or 5B00000 for DFM-06 (very old DFM-06 stop here, don't have ID), the DFM-09-type null-subframe is n000000 followed by the (n+1)Cxxxxy ID-subframe. Some have even more then one null-subframe, like the pilotsonde, seems to fill-up the "channels" until the sonde_id-subframe.

But there will be still some delay if the same decoder is running with changing DFM-input. This also affects temperature.
The sonde_id is not displayed every frame, but the --json output is different, there will be a delay. I initialize or reset the json_sonde_id[] to the dummy-string. If the sonde_id in the json-blob could be the empty string (maybe looks better), there are 3 places to uncomment //json_sonde_id[0] = '\0';

With auto_rx maybe you re-start the decoder for a new dfm in the spectrum. However sometimes there are two dfm's on the same frequency at the same time. With rs41 this is not such a problem, since every frame includes the ID.

Now only DFM-06 and DFM-09 have IDs with this name. For pilotsondes and DFM-17 I went back to using the channel-number and switched off temperature, since I don't have enough information about the test sondes.

All in all the --auto option seems better, in principle it could detect IDs that were unknown before.

If you want to test, try:
./dfm09dm_dft --ecc --auto -vv --ptu (audio)
./dfm09dm_dft --dist --auto -vv --ptu (audio)
./dfm09dm_dft --json --auto -vv --ptu (audio)

-vv shows the polarity [+/-] and the corrected bits in a block (0,1,..).
--dist gives more reliable/unique frames (depending on the ecc-threshold), the subframes have to be in 1 frame distance. Then the coordinates should be the same everywhere, only the temperature could differ. Same for --json (both include --ecc). Can be used togehter, but with only --json you see bad frames that are not used by --json.

**Comment by rs1729** [comment]
By the way, rs41 has the --sat option to put out the ublox packets in GPS1,GPS2,GPS3.
https://www.fingers-welt.de/phpBB/viewtopic.php?f=14&t=43&start=1975#p163997

The GPS data in the frames for rs41, m10 and dfm are certain binary packets from the GPS chip, sometimes with some minor modifications (e.g. signal quality). You find them in the GPS specifications (ublox, trimble, navman/telit/sirf). Usually the manufacturers stick with a certain GPS chip quite long, only Graw seems to try the whole product line of a vendor ... (I hear there are even graw-pilotsondes with ublox)

So if you look for battery voltage, there are not so many places left...

**Pull request merged**
