### PR TITLE
demod_mod: simplify Makefile

### PR DESCRIPTION
**Pull request by pinkavaj**

### CODE REVIEW

**Comment by rs1729** [comment]
Two issues here:
1) `lms6mod` is deprecated (not maintained anymore), `lms6Xmod` does both. As I said, there are some older version here and there...
2) I want `-Ofast` for `demod_mod.c`, speeds up calculations with floats a lot, FFT and lowpass. Possible inaccuracies are negligible. (Same for `imet4iq.c`, `mk2a1680mod.c`, `dft_detect.c`.)

**Comment by pinkavaj** [comment]
1. `lms6mod` removed
2. fixed for `demod_mod.c`, I did not touched the others (yet).

**Comment by rs1729** [comment]
`gcc -O3 -Ofast   -c -o demod_mod.o demod_mod.c`
is as good as just `-Ofast`, i.e. `-Ofast`won't be discarded?
Just asking, seems to perform the same, though.

One more thing,
the old `*.o`-files are not cleaned, my fault, didn't have this before (and got a segfault now... ;).
Is there a simple way to delete also the o-files, other than `rm *.o`?

**Comment by rs1729** [comment]
ok, I see, I didn't clean `rs92mod.o`, `rs41mod.o` etc., because they were not produced before.
`-O3 -Ofast` should be ok, but could you include cleaning all the produced o-files?

Perhaps `rm -f *.o`will do, also for `demod_mod.o`, `bch_ecc_mod.o`.

**Comment by pinkavaj** [comment]
If multiple `-Oxxx` are passed, the only the last one is the actually used, so this should be ok.

Added clean-up for all the `*.o`, thx for spotting that!

**Comment by rs1729** [comment]
Thanks!

**Pull request merged**
